"""split students fullname

Revision ID: 004f213fd314
Revises: f7c94fe6b383
Create Date: 2024-10-06 15:37:48.054164

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "004f213fd314"
down_revision: Union[str, None] = "f7c94fe6b383"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "students", sa.Column("first_name", sa.String(length=120), nullable=False)
    )
    op.add_column(
        "students", sa.Column("last_name", sa.String(length=120), nullable=False)
    )
    op.drop_index("ix_students_fullname", table_name="students")
    op.create_index(
        op.f("ix_students_first_name"), "students", ["first_name"], unique=False
    )
    op.create_index(
        op.f("ix_students_last_name"), "students", ["last_name"], unique=False
    )
    op.drop_column("students", "fullname")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "students",
        sa.Column(
            "fullname", sa.VARCHAR(length=120), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_students_last_name"), table_name="students")
    op.drop_index(op.f("ix_students_first_name"), table_name="students")
    op.create_index("ix_students_fullname", "students", ["fullname"], unique=False)
    op.drop_column("students", "last_name")
    op.drop_column("students", "first_name")
    # ### end Alembic commands ###
